server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React routing
    location / {
        try_files $uri /index.html;
    }

    # API proxy
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://server:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
